import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import AppLayout from './components/AppLayout';

export default function Home() {
  return (
    <>
      <AppLayout>
        <Head>
          <title>boarDev</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>
            <a href="https://nextjs.org">boarDev!</a>
          </h1>
          <h1 className="subTitle">Tu pizarra definitiva</h1>
          <nav>
            <Link href="/timeline">
              <a>boardTimeLine</a>
            </Link>
          </nav>
        </main>
      </AppLayout>

      {/* Estilos dentro del propio componente con JSX */}
      <style jsx>{`
        h1.subTitle {
          color: orange;
          font-size: 25px;
        }
        nav {
          color: red;
          font-size: 20px;
        }
      `}</style>
      <style global jsx>{`
        body {
        }
      `}</style>
    </>
  );
}
