import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import AppLayout from './components/AppLayout';
import styles from '../styles/Home.module.css';
import { fonts } from '../styles/theme'; // Importa las fuentes de theme.js

export default function Home() {
  return (
    <>
      <AppLayout>
        {' '}
        {/* Es la plantilla de cosas comunes para todas las vistas */}
        <Head>
          <title>boarDev</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <main className={styles.main}> */}
        <h1 className={styles.title}>
          <a href="https://nextjs.org">boarDev!</a>
        </h1>
        {/* </main> */}
      </AppLayout>

      {/* Estilos dentro del propio componente con JSX */}
      <style jsx>{`
        h1 {
          font-family: ${fonts.base};
        }
      `}</style>
      <style global jsx>{``}</style>
    </>
  );
}
