import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>boarDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">boarDev!</a>
        </h1>
        <nav>
          <a href="/boardtimeline">boardTimeLine</a>
        </nav>

        {/* Estilos dentro del propio componente con JSX */}
        <style jsx>{`
          nav {
            color: red;
            font-size: 20px;
          }
        `}</style>
        <style global jsx>{`
          body {
          }
        `}</style>
      </main>
    </div>
  );
}
